// Navbar scroll effect
const navbar = document.getElementById('navbar');
window.addEventListener('scroll', () => {
  if (window.scrollY > 40) navbar.classList.add('scrolled');
  else navbar.classList.remove('scrolled');
}, { passive: true });

// Mobile menu
const navToggle = document.getElementById('navToggle');
const navLinks = document.getElementById('navLinks');
if (navToggle && navLinks) {
  navToggle.addEventListener('click', () => {
    navLinks.classList.toggle('open');
  });
  navLinks.querySelectorAll('a').forEach(a => {
    a.addEventListener('click', () => navLinks.classList.remove('open'));
  });
}

// Scroll reveal
const reveals = document.querySelectorAll('.reveal');
const revealObserver = new IntersectionObserver((entries) => {
  entries.forEach(e => { if (e.isIntersecting) { e.target.classList.add('visible'); revealObserver.unobserve(e.target); } });
}, { threshold: 0.12 });
reveals.forEach(el => revealObserver.observe(el));

// ── Traducciones ES / EN ─────────────────────────────────────
const T = {
  es: {
    nav_inicio:'Inicio', nav_quienes:'Quiénes somos', nav_sport:'i-Motion Sport',
    nav_esthetic:'i-Shape Esthetic', nav_online:'i-Motion Online', nav_reservar:'Reservar sesión',
    on_hero_title:'Tu entrenamiento y nutrición<br><span style="color:#4da6e0">donde y cuando quieras</span>',
    on_hero_sub:'La plataforma de i-Motion EMS Tenerife para llevar tu entrenamiento y nutrición al siguiente nivel — en casa, en el gimnasio o donde estés.',
    on_hero_btn:'Empezar ahora',
    on_stat1:'Personalizado', on_stat2:'Disponible', on_stat3:'Evaluación mensual',
    on_feat_tag:'Qué incluye', on_feat_title:'Una plataforma completa para <span class="accent">tu cambio</span>',
    on_f1t:'Entrenamiento personalizado', on_f1p:'Plan de entrenamiento adaptado a tus objetivos, nivel y equipamiento disponible.',
    on_f2t:'Plan nutricional', on_f2p:'Alimentación adaptada a ti, con macronutrientes, recetas y hábitos saludables.',
    on_f3t:'Seguimiento de progreso', on_f3p:'Control de hábitos, resultados y motivación continua desde la app.',
    on_f4t:'Evaluación mensual en centro', on_f4p:'Una vez al mes en Tenerife Top Training para medir tu composición corporal y ver tus progresos.',
    on_bonos_tag:'Elige tu plan', on_bonos_title:'Para cada <span class="accent">perfil</span>',
    on_bonos_sub:'Tanto si ya entrenas con nosotros como si buscas empezar desde cero',
    on_b1_badge:'⚡ Cliente con bono activo',
    on_b1_title:'i-Motion Online + EMS',
    on_b1_desc:'Si ya entrenas con nosotros en el centro, complementa tus sesiones EMS con entrenamiento y nutrición online a precio especial.',
    on_b1_l1:'Plan de entrenamiento online personalizado', on_b1_l2:'Plan nutricional adaptado',
    on_b1_l3:'Seguimiento y motivación continua', on_b1_l4:'Evaluación corporal mensual en centro',
    on_b1_l5:'Precio especial para clientes activos', on_b1_l6:'Comunicación directa con tu entrenador',
    on_b2_badge:'🌱 Nuevo cliente', on_b2_title:'i-Motion Online',
    on_b2_desc:'Empieza tu transformación desde casa, el gimnasio o donde estés. Entrenamiento y nutrición profesional al alcance de tu móvil.',
    on_b2_l1:'Plan de entrenamiento online personalizado', on_b2_l2:'Plan nutricional adaptado a tus objetivos',
    on_b2_l3:'Seguimiento semanal de progreso', on_b2_l4:'Evaluación corporal mensual en centro',
    on_b2_l5:'Comunicación directa con tu entrenador', on_b2_l6:'Acceso completo a la app i-Motion',
    on_btn_subs:'Suscribirme', on_btn_subs2:'Empezar ahora',
    on_plat_tag:'La plataforma', on_plat_title:'Todo en <span class="accent">una app</span>', on_plat_sub:'Tecnología profesional al servicio de tu progreso',
    on_p1t:'Planes 100% personalizados', on_p1p:'Entrenamientos adaptados a tu nivel y objetivos.',
    on_p2t:'Actualización periódica', on_p2p:'Tu plan evoluciona contigo según tus progresos.',
    on_p3t:'Seguimiento y motivación', on_p3p:'Control de hábitos, progreso y resultados en tiempo real.',
    on_p4t:'Comunicación directa', on_p4p:'Resuelve dudas y recibe el apoyo que necesitas.',
    on_cta_title:'¿Listo para entrenar donde y cuando <span class="accent">quieras</span>?',
    on_cta_sub:'Únete a i-Motion Online y lleva tu entrenamiento y nutrición al siguiente nivel.',
    on_cta_btn:'Empezar ahora ⚡',
    foot_nav:'Navegación', foot_contact:'Contacto',
    foot_rights:'© 2025 i-Motion EMS Tenerife · Todos los derechos reservados',
    foot_legal:'Aviso Legal', foot_privacy:'Privacidad', foot_cookies:'Cookies',
    idx_badge:'🏆 Tenerife Top Training · La Caleta · Costa Adeje · Tenerife',
    idx_sub:'El centro de electroestimulación muscular de referencia en Tenerife. 25 minutos que transforman tu cuerpo, en Costa Adeje en el Tenerife Top Training.',
    idx_btn1:'Reservar sesión gratis', idx_btn2:'Conocer más',
    idx_stat1:'por sesión', idx_stat2:'músculos activados', idx_stat3:'personalizado', idx_stat4:'Training Tenerife',
    idx_intro_tag:'¿Qué es EMS?',
    idx_intro_title:'<span class="accent">i-Motion EMS Tenerife</span> — La revolución del entrenamiento inteligente',
    idx_intro_p1:'La electroestimulación muscular (EMS) utiliza impulsos eléctricos de baja frecuencia para activar simultáneamente hasta el 90% de tus fibras musculares — algo imposible con el entrenamiento convencional.',
    idx_intro_p2:'Estamos en <strong style="color:#fff;">Tenerife Top Training</strong>, el centro de alto rendimiento de referencia en Tenerife, en <strong style="color:#fff;">Av. de Los Acantilados s/n, La Caleta, Costa Adeje</strong>. Un espacio de élite para un entrenamiento de élite.',
    idx_intro_btn:'Sobre nosotros',
    idx_serv_tag:'Nuestros programas', idx_serv_title:'Elige tu <span class="accent">objetivo</span>',
    idx_sport_tag:'Rendimiento', idx_sport_desc:'Para atletas y deportistas que buscan llevar su rendimiento al siguiente nivel. Mejora fuerza, resistencia y potencia muscular con entrenamientos adaptados a tu deporte.',
    idx_sport_btn:'Ver programa',
    idx_esthetic_tag:'Estético', idx_esthetic_desc:'Para quienes buscan una transformación corporal visible. Tonifica, reduce celulitis y mejora la firmeza con electroestimulación focalizada en zonas específicas.',
    idx_esthetic_btn:'Ver programa',
    idx_benef_tag:'Por qué i-Motion EMS Tenerife', idx_benef_title:'Ventajas del entrenamiento <span class="accent">i-Motion</span>',
    idx_b2t:'Ahorra tiempo', idx_b2p:'25 minutos = 90 minutos de gym convencional',
    idx_b3t:'Aumenta masa muscular', idx_b3p:'Activa hasta el 90% de las fibras musculares',
    idx_b4t:'Tonificación y adelgazamiento', idx_b4p:'Define tu cuerpo y reduce grasa con resultados visibles y rápidos',
    idx_b5t:'Descarga articulaciones', idx_b5p:'Sin impacto, ideal para lesiones y rehabilitación',
    idx_b6t:'100% personalizado', idx_b6p:'Programas adaptados a tu cuerpo y objetivos',
    idx_results_tag:'Resultados reales', idx_results_title:'Antes y después con <span class="accent">i-Motion EMS</span>',
    idx_results_sub:'Transformaciones reales de clientes reales. Resultados visibles en pocas semanas.',
    idx_tech_tag:'Tecnología', idx_tech_title:'Equipo <span class="accent">i-motion Pro V25</span>',
    idx_tech_sub:'La última generación en electroestimulación muscular inalámbrica con inteligencia artificial integrada',
    idx_cta_title:'¿Listo para entrenar en <span class="accent">Tenerife Top Training</span> con EMS?',
    idx_cta_sub:'Reserva tu primera sesión de prueba gratuita en i-Motion EMS Tenerife',
    idx_cta_btn:'Reservar sesión gratis',
    sp_b1:'Entrenamiento de fuerza y resistencia', sp_b2:'Mejora del rendimiento deportivo',
    sp_b3:'Recuperación muscular acelerada', sp_b4:'Tonificación y definición corporal', sp_b5:'Traje cuerpo entero o inferior',
    es_b1:'Reducción de celulitis', es_b2:'Mejora de la firmeza cutánea',
    es_b3:'Fortalecimiento suelo pélvico', es_b4:'Resultados visibles desde la 1ª sesión',
    qs_hero_tag:'Sobre nosotros', qs_hero_title:'QUIÉNES <span class="accent">SOMOS</span>',
    qs_hero_sub:'El primer centro especializado en entrenamiento EMS de Av. Los Acantilados s/n, La Caleta, Costa Adeje.',
    qs_mission_tag:'Nuestra misión', qs_mission_title:'Tecnología al servicio de tu <span class="accent">bienestar</span>',
    qs_p1:'En i-Motion Tenerife EMS creemos que cada persona merece acceder a la tecnología más avanzada en entrenamiento físico, con resultados reales y en el menor tiempo posible.',
    qs_p2:'Nuestro centro, ubicado en Costa Adeje, está equipado con la última generación del sistema i-motion Pro V25, combinando electroestimulación inalámbrica con inteligencia artificial para maximizar cada sesión.',
    qs_p3:'Contamos con entrenadores certificados en EMS que diseñan programas completamente personalizados, adaptados a tus objetivos, condición física y estilo de vida.',
    qs_values_tag:'Nuestros valores', qs_values_title:'Por qué elegir <span class="accent">i-Motion</span>',
    qs_v1t:'100% Personalizado', qs_v1p:'Cada sesión se adapta a tus objetivos y condición física con seguimiento constante.',
    qs_v2t:'Entrenadores Certificados', qs_v2p:'Profesionales especializados en EMS con formación continua y experiencia demostrada.',
    qs_v3t:'Tecnología V25', qs_v3p:'El sistema más avanzado del mercado con IA integrada y conectividad Bluetooth.',
    qs_centro_tag:'Nuestro centro', qs_centro_title:'Un espacio creado para <span class="accent">ti</span>',
    qs_centro_sub:'Instalaciones modernas y equipadas en Costa Adeje, con un ambiente acogedor donde te sentirás cómodo desde el primer día.',
    qs_c1t:'Tenerife Top Training — Centro de Alto Rendimiento', qs_c1p:'Situados dentro del centro deportivo de referencia en Tenerife, con instalaciones de élite.',
    qs_c2t:'Ubicación privilegiada', qs_c2p:'Av. de Los Acantilados s/n, La Caleta, Costa Adeje — fácil acceso y aparcamiento.',
    qs_c3t:'Todo incluido', qs_c3p:'Traje EMS, toalla y asesoramiento nutricional básico incluidos.',
    qs_c4t:'Horarios flexibles', qs_c4p:'Adaptamos la sesión a tu agenda. Mañana, tarde o noche.',
    qs_c5t:'Seguimiento continuo', qs_c5p:'Medición de resultados y ajuste del programa mensualmente.',
    qs_visit_btn:'Visítanos',
    sp_hero_tag:'Rendimiento deportivo', sp_hero_sub:'Entrenamiento de alto rendimiento con electroestimulación muscular para atletas y deportistas.',
    sp_prog_tag:'El programa', sp_prog_title:'Lleva tu rendimiento al <span class="accent">siguiente nivel</span>',
    sp_prog_p1:'El programa i-Motion Sport está diseñado para deportistas y atletas que buscan superar sus límites.',
    sp_prog_p2:'Disponemos de dos modalidades: el <strong style="color:#fff;">traje cuerpo entero</strong> y el <strong style="color:#fff;">traje inferior</strong>.',
    sp_prog_btn:'Empezar ahora',
    sp_equip_tag:'Equipamiento', sp_equip_title:'Elige tu <span class="accent">traje EMS</span>', sp_equip_sub:'Dos opciones adaptadas a tus objetivos deportivos',
    sp_suit1:'Traje Cuerpo Entero', sp_suit1p:'Activa simultáneamente toda la musculatura del cuerpo.',
    sp_suit2badge:'Tren inferior', sp_suit2:'Traje Inferior', sp_suit2p:'Especializado en piernas, glúteos y zona lumbar.',
    sp_benef_tag:'Beneficios', sp_benef_title:'Resultados <span class="accent">demostrados</span>',
    sp_b1t:'Fuerza explosiva', sp_b1p:'Aumenta la potencia muscular hasta un 30% en 8 semanas',
    sp_b2t:'Mayor resistencia', sp_b2p:'Mejora el rendimiento cardiovascular y retarda la fatiga',
    sp_b3t:'Recuperación rápida', sp_b3p:'Reduce el tiempo de recuperación entre entrenamientos',
    sp_b4t:'Prevención de lesiones', sp_b4p:'Fortalece la musculatura estabilizadora',
    sp_b5t:'Conexión neuromuscular', sp_b5p:'Mejora la coordinación y activación muscular específica',
    sp_b6t:'Eficiencia máxima', sp_b6p:'25 minutos = 90 minutos de gym convencional',
    sp_b7t:'Tonificación y adelgazamiento', sp_b7p:'Reduce grasa corporal y define la musculatura',
    sp_results_tag:'Transformaciones reales', sp_results_title:'Antes y después con <span class="accent">i-Motion Sport</span>', sp_results_sub:'Resultados reales de deportistas que entrenan con EMS',
    sp_cta_title:'¿Preparado para entrenar como un <span class="accent">profesional</span>?',
    sp_cta_sub:'Primera sesión de prueba gratuita en Tenerife Top Training, Costa Adeje.',
    sp_cta_btn:'Reservar ahora',
    es_hero_tag:'Transformación corporal', es_hero_sub:'Tonifica tu cuerpo, reduce la celulitis y mejora la firmeza.',
    es_prog_tag:'El programa', es_prog_title:'Tu transformación <span class="accent">empieza aquí</span>',
    es_prog_p1:'El programa i-Shape Esthetic utiliza electroestimulación muscular focalizada para trabajar zonas específicas.',
    es_prog_p2:'A diferencia del entrenamiento convencional, el EMS permite activar músculos profundos con resultados visibles desde las primeras sesiones.',
    es_prog_btn:'Reservar sesión gratis',
    es_tech_tag:'Tecnología i-Shape', es_tech_title:'El equipo <span class="accent">más avanzado</span>', es_tech_sub:'Diseñado específicamente para la transformación estética corporal',
    es_gear1:'Traje i-Shape EMS con electrodos integrados', es_gear2:'Estimulación focalizada en glúteos y piernas', es_gear3:'Zonas de activación muscular profunda',
    es_benef_tag:'Resultados', es_benef_title:'Lo que conseguirás con <span class="accent">i-Shape</span>',
    es_b1t:'Tonificación corporal', es_b1p:'Define y tonifica todo tu cuerpo de forma proporcional',
    es_b2t:'Reduce la celulitis', es_b2p:'Mejora la circulación y reduce la piel de naranja',
    es_b3t:'Piel más firme', es_b3p:'Estimula la producción de colágeno y mejora la elasticidad',
    es_b4t:'Control del peso', es_b4p:'Aumenta el metabolismo basal, quemando más calorías en reposo',
    es_b5t:'Zonas específicas', es_b5p:'Trabaja exactamente donde más lo necesitas',
    es_b6t:'Resultados rápidos', es_b6p:'Cambios visibles desde la primera sesión',
    es_b7t:'Fortalecimiento suelo pélvico', es_b7p:'Electroestimulación específica para el suelo pélvico',
    es_video_tag:'Transformaciones reales', es_video_title:'Antes y después <span class="accent">en vídeo</span>', es_video_sub:'Resultados reales de clientes reales con i-Shape Esthetic',
    es_photo_tag:'Fotos reales', es_photo_title:'Resultados <span class="accent">demostrados</span>',
    es_process_tag:'Cómo funciona', es_process_title:'Tu sesión <span class="accent">paso a paso</span>',
    es_s1t:'Evaluación inicial', es_s1p:'Analizamos tu composición corporal y definimos tus objetivos.',
    es_s2t:'Equipamiento', es_s2p:'Te colocamos el traje i-Shape calibrado para tu cuerpo.',
    es_s3t:'Sesión de 25 minutos', es_s3p:'Relajación guiada con electroestimulación activa y controlada.',
    es_s4t:'Seguimiento', es_s4p:'Medición de resultados y ajuste del programa cada mes.',
    es_process_btn:'Reservar sesión gratis',
    es_cta_title:'Transforma tu cuerpo en <span class="accent">tiempo récord</span>',
    es_cta_sub:'Primera sesión de prueba gratuita en Tenerife Top Training, Costa Adeje.',
    es_cta_btn:'Quiero empezar',
    ct_hero_tag:'Empezar es gratis', ct_hero_sub:'Primera sesión de prueba completamente gratuita y sin compromiso.',
    ct_form_tag:'Escríbenos', ct_form_title:'Ponte en <span class="accent">contacto</span>',
    ct_f_nombre:'Nombre *', ct_f_apellidos:'Apellidos', ct_f_email:'Email *', ct_f_tel:'Teléfono',
    ct_f_programa:'Programa de interés', ct_select:'Seleccionar...',
    ct_prog1:'i-Motion Sport (rendimiento deportivo)', ct_prog2:'i-Shape Esthetic (transformación corporal)', ct_prog3:'Ambos programas / No lo sé todavía',
    ct_f_fecha:'Fecha preferida para la sesión', ct_f_horario:'Horario preferido',
    ct_h1:'Mañana (8:00 – 13:00)', ct_h2:'Tarde (13:00 – 18:00)', ct_h3:'Noche (18:00 – 21:00)', ct_h4:'Sábado (9:00 – 14:00)',
    ct_f_como:'¿Cómo nos conociste?',
    ct_c3:'Google / Búsqueda en internet', ct_c4:'Recomendación de un amigo o familiar', ct_c5:'Pasando por el centro', ct_c6:'Otro',
    ct_f_msg:'Mensaje', ct_f_privacy:'Acepto la <a href="politica-privacidad.html" style="color:var(--accent);">política de privacidad</a> *',
    ct_submit:'Enviar solicitud de reserva',
    ct_info_tag:'Información', ct_info_title:'Encuéntranos <span class="accent">aquí</span>',
    ct_phone:'Teléfono', ct_address:'Dirección', ct_hours_label:'Horario',
    ct_hours:'Lunes a Viernes: 8:00 – 21:00<br>Sábados: 9:00 – 14:00',
  },
  en: {
    nav_inicio:'Home', nav_quienes:'About us', nav_sport:'i-Motion Sport',
    nav_esthetic:'i-Shape Esthetic', nav_online:'i-Motion Online', nav_reservar:'Book a session',
    on_hero_title:'Your training and nutrition<br><span style="color:#4da6e0">where and when you want</span>',
    on_hero_sub:'The i-Motion EMS Tenerife platform to take your training and nutrition to the next level — at home, at the gym or wherever you are.',
    on_hero_btn:'Start now',
    on_stat1:'Personalised', on_stat2:'Available', on_stat3:'Monthly assessment',
    on_feat_tag:'What\'s included', on_feat_title:'A complete platform for <span class="accent">your transformation</span>',
    on_f1t:'Personalised training', on_f1p:'Training plan adapted to your goals, level and available equipment.',
    on_f2t:'Nutrition plan', on_f2p:'Diet tailored to you, with macronutrients, recipes and healthy habits.',
    on_f3t:'Progress tracking', on_f3p:'Habit control, results and continuous motivation from the app.',
    on_f4t:'Monthly assessment at centre', on_f4p:'Once a month at Tenerife Top Training to measure your body composition and see your progress.',
    on_bonos_tag:'Choose your plan', on_bonos_title:'For every <span class="accent">profile</span>',
    on_bonos_sub:'Whether you already train with us or are looking to start from scratch',
    on_b1_badge:'⚡ Active member',
    on_b1_title:'i-Motion Online + EMS',
    on_b1_desc:'If you already train with us at the centre, complement your EMS sessions with online training and nutrition at a special price.',
    on_b1_l1:'Personalised online training plan', on_b1_l2:'Adapted nutrition plan',
    on_b1_l3:'Continuous follow-up and motivation', on_b1_l4:'Monthly body assessment at centre',
    on_b1_l5:'Special price for active members', on_b1_l6:'Direct communication with your trainer',
    on_b2_badge:'🌱 New client', on_b2_title:'i-Motion Online',
    on_b2_desc:'Start your transformation from home, the gym or wherever you are. Professional training and nutrition at your fingertips.',
    on_b2_l1:'Personalised online training plan', on_b2_l2:'Nutrition plan adapted to your goals',
    on_b2_l3:'Weekly progress tracking', on_b2_l4:'Monthly body assessment at centre',
    on_b2_l5:'Direct communication with your trainer', on_b2_l6:'Full access to the i-Motion app',
    on_btn_subs:'Subscribe', on_btn_subs2:'Start now',
    on_plat_tag:'The platform', on_plat_title:'Everything in <span class="accent">one app</span>', on_plat_sub:'Professional technology at the service of your progress',
    on_p1t:'100% personalised plans', on_p1p:'Workouts adapted to your level and goals.',
    on_p2t:'Regular updates', on_p2p:'Your plan evolves with you as you progress.',
    on_p3t:'Tracking and motivation', on_p3p:'Habit control, progress and real-time results.',
    on_p4t:'Direct communication', on_p4p:'Get answers and the support you need.',
    on_cta_title:'Ready to train where and when <span class="accent">you want</span>?',
    on_cta_sub:'Join i-Motion Online and take your training and nutrition to the next level.',
    on_cta_btn:'Start now ⚡',
    foot_nav:'Navigation', foot_contact:'Contact',
    foot_rights:'© 2025 i-Motion EMS Tenerife · All rights reserved',
    foot_legal:'Legal Notice', foot_privacy:'Privacy', foot_cookies:'Cookies',
    idx_badge:'🏆 Tenerife Top Training · La Caleta · Costa Adeje · Tenerife',
    idx_sub:'The leading electric muscle stimulation centre in Tenerife. 25 minutes that transform your body, at Tenerife Top Training in Costa Adeje.',
    idx_btn1:'Book a free session', idx_btn2:'Learn more',
    idx_stat1:'per session', idx_stat2:'muscles activated', idx_stat3:'personalised', idx_stat4:'Training Tenerife',
    idx_intro_tag:'What is EMS?',
    idx_intro_title:'<span class="accent">i-Motion EMS Tenerife</span> — The smart training revolution',
    idx_intro_p1:'Electric Muscle Stimulation (EMS) uses low-frequency electrical impulses to simultaneously activate up to 90% of your muscle fibres — impossible with conventional training.',
    idx_intro_p2:'We are located at <strong style="color:#fff;">Tenerife Top Training</strong>, the island\'s leading high-performance centre, at <strong style="color:#fff;">Av. de Los Acantilados s/n, La Caleta, Costa Adeje</strong>.',
    idx_intro_btn:'About us',
    idx_serv_tag:'Our programmes', idx_serv_title:'Choose your <span class="accent">goal</span>',
    idx_sport_tag:'Performance', idx_sport_desc:'For athletes looking to take their performance to the next level. Improve strength, endurance and muscle power with training tailored to your sport.',
    idx_sport_btn:'View programme',
    idx_esthetic_tag:'Aesthetic', idx_esthetic_desc:'For those seeking visible body transformation. Tone, reduce cellulite and improve firmness with targeted electrostimulation.',
    idx_esthetic_btn:'View programme',
    idx_benef_tag:'Why i-Motion EMS Tenerife', idx_benef_title:'Benefits of <span class="accent">i-Motion</span> training',
    idx_b2t:'Save time', idx_b2p:'25 minutes = 90 minutes of conventional gym',
    idx_b3t:'Build muscle mass', idx_b3p:'Activates up to 90% of muscle fibres',
    idx_b4t:'Toning and weight loss', idx_b4p:'Define your body and reduce fat with fast, visible results',
    idx_b5t:'Joint-friendly', idx_b5p:'No impact, ideal for injuries and rehabilitation',
    idx_b6t:'100% personalised', idx_b6p:'Programmes tailored to your body and goals',
    idx_results_tag:'Real results', idx_results_title:'Before and after with <span class="accent">i-Motion EMS</span>',
    idx_results_sub:'Real transformations from real clients. Visible results in just a few weeks.',
    idx_tech_tag:'Technology', idx_tech_title:'<span class="accent">i-motion Pro V25</span> equipment',
    idx_tech_sub:'The latest generation in wireless EMS with integrated artificial intelligence',
    idx_cta_title:'Ready to train at <span class="accent">Tenerife Top Training</span> with EMS?',
    idx_cta_sub:'Book your first free trial session at i-Motion EMS Tenerife',
    idx_cta_btn:'Book a free session',
    sp_b1:'Strength and endurance training', sp_b2:'Sports performance improvement',
    sp_b3:'Accelerated muscle recovery', sp_b4:'Toning and body definition', sp_b5:'Full-body or lower-body suit',
    es_b1:'Cellulite reduction', es_b2:'Improved skin firmness',
    es_b3:'Pelvic floor strengthening', es_b4:'Visible results from the 1st session',
    qs_hero_tag:'About us', qs_hero_title:'WHO <span class="accent">WE ARE</span>',
    qs_hero_sub:'The first specialist EMS training centre at Av. Los Acantilados s/n, La Caleta, Costa Adeje.',
    qs_mission_tag:'Our mission', qs_mission_title:'Technology in the service of your <span class="accent">wellbeing</span>',
    qs_p1:'At i-Motion Tenerife EMS we believe everyone deserves access to the most advanced fitness technology, with real results in the shortest time possible.',
    qs_p2:'Our centre in Costa Adeje is equipped with the latest i-motion Pro V25 system, combining wireless electrostimulation with artificial intelligence.',
    qs_p3:'Our EMS-certified trainers design fully personalised programmes tailored to your goals, fitness level and lifestyle.',
    qs_values_tag:'Our values', qs_values_title:'Why choose <span class="accent">i-Motion</span>',
    qs_v1t:'100% Personalised', qs_v1p:'Every session is adapted to your goals and fitness level with constant monitoring.',
    qs_v2t:'Certified Trainers', qs_v2p:'EMS specialists with continuous training and proven experience.',
    qs_v3t:'V25 Technology', qs_v3p:'The most advanced system on the market with integrated AI and Bluetooth connectivity.',
    qs_centro_tag:'Our centre', qs_centro_title:'A space created for <span class="accent">you</span>',
    qs_centro_sub:'Modern, fully equipped facilities in Costa Adeje, with a welcoming atmosphere from day one.',
    qs_c1t:'Tenerife Top Training — High Performance Centre', qs_c1p:'Located within Tenerife\'s leading sports centre, with elite facilities.',
    qs_c2t:'Prime location', qs_c2p:'Av. de Los Acantilados s/n, La Caleta, Costa Adeje — easy access and parking.',
    qs_c3t:'All inclusive', qs_c3p:'EMS suit, towel and basic nutritional advice included.',
    qs_c4t:'Flexible hours', qs_c4p:'We adapt the session to your schedule. Morning, afternoon or evening.',
    qs_c5t:'Continuous monitoring', qs_c5p:'Results measured and programme adjusted every month.',
    qs_visit_btn:'Visit us',
    sp_hero_tag:'Sports performance', sp_hero_sub:'High-performance training with EMS for athletes and sports enthusiasts.',
    sp_prog_tag:'The programme', sp_prog_title:'Take your performance to the <span class="accent">next level</span>',
    sp_prog_p1:'The i-Motion Sport programme is designed for athletes who want to push their limits.',
    sp_prog_p2:'We offer two options: the <strong style="color:#fff;">full-body suit</strong> and the <strong style="color:#fff;">lower-body suit</strong>.',
    sp_prog_btn:'Start now',
    sp_equip_tag:'Equipment', sp_equip_title:'Choose your <span class="accent">EMS suit</span>', sp_equip_sub:'Two options tailored to your sports goals',
    sp_suit1:'Full-Body Suit', sp_suit1p:'Simultaneously activates all body muscles.',
    sp_suit2badge:'Lower body', sp_suit2:'Lower-Body Suit', sp_suit2p:'Specialised in legs, glutes and lower back.',
    sp_benef_tag:'Benefits', sp_benef_title:'Proven <span class="accent">results</span>',
    sp_b1t:'Explosive strength', sp_b1p:'Increases muscle power by up to 30% in 8 weeks',
    sp_b2t:'Greater endurance', sp_b2p:'Improves cardiovascular performance and delays fatigue',
    sp_b3t:'Fast recovery', sp_b3p:'Reduces recovery time between training sessions',
    sp_b4t:'Injury prevention', sp_b4p:'Strengthens stabilising muscles',
    sp_b5t:'Neuromuscular connection', sp_b5p:'Improves coordination and specific muscle activation',
    sp_b6t:'Maximum efficiency', sp_b6p:'25 minutes = 90 minutes of conventional gym',
    sp_b7t:'Toning and weight loss', sp_b7p:'Reduces body fat and defines muscles',
    sp_results_tag:'Real transformations', sp_results_title:'Before and after with <span class="accent">i-Motion Sport</span>', sp_results_sub:'Real results from athletes who train with EMS',
    sp_cta_title:'Ready to train like a <span class="accent">professional</span>?',
    sp_cta_sub:'First free trial session at Tenerife Top Training, Costa Adeje.',
    sp_cta_btn:'Book now',
    es_hero_tag:'Body transformation', es_hero_sub:'Tone your body, reduce cellulite and improve firmness with targeted electrostimulation.',
    es_prog_tag:'The programme', es_prog_title:'Your transformation <span class="accent">starts here</span>',
    es_prog_p1:'The i-Shape Esthetic programme uses targeted electric muscle stimulation to work specific areas of the body.',
    es_prog_p2:'Unlike conventional training, EMS activates deep muscles, delivering visible results from the very first sessions.',
    es_prog_btn:'Book a free session',
    es_tech_tag:'i-Shape Technology', es_tech_title:'The most <span class="accent">advanced equipment</span>', es_tech_sub:'Specifically designed for aesthetic body transformation',
    es_gear1:'i-Shape EMS suit with integrated electrodes', es_gear2:'Targeted stimulation on glutes and legs', es_gear3:'Deep muscle activation zones',
    es_benef_tag:'Results', es_benef_title:'What you will achieve with <span class="accent">i-Shape</span>',
    es_b1t:'Body toning', es_b1p:'Define and tone your whole body proportionally',
    es_b2t:'Reduce cellulite', es_b2p:'Improves circulation and reduces orange-peel skin',
    es_b3t:'Firmer skin', es_b3p:'Stimulates collagen production and improves elasticity',
    es_b4t:'Weight management', es_b4p:'Boosts basal metabolism, burning more calories at rest',
    es_b5t:'Targeted areas', es_b5p:'Works exactly where you need it most',
    es_b6t:'Fast results', es_b6p:'Visible changes from the very first session',
    es_b7t:'Pelvic floor strengthening', es_b7p:'Specific electrostimulation to strengthen the pelvic floor muscles',
    es_video_tag:'Real transformations', es_video_title:'Before and after <span class="accent">on video</span>', es_video_sub:'Real results from real clients with i-Shape Esthetic',
    es_photo_tag:'Real photos', es_photo_title:'Proven <span class="accent">results</span>',
    es_process_tag:'How it works', es_process_title:'Your session <span class="accent">step by step</span>',
    es_s1t:'Initial assessment', es_s1p:'We analyse your body composition and define your goals.',
    es_s2t:'Equipment', es_s2p:'We fit the i-Shape suit calibrated to your body.',
    es_s3t:'25-minute session', es_s3p:'Guided relaxation with active, controlled electrostimulation.',
    es_s4t:'Follow-up', es_s4p:'Results measured and programme adjusted every month.',
    es_process_btn:'Book a free session',
    es_cta_title:'Transform your body in <span class="accent">record time</span>',
    es_cta_sub:'First free trial session at Tenerife Top Training, Costa Adeje.',
    es_cta_btn:'I want to start',
    ct_hero_tag:'Starting is free', ct_hero_sub:'First trial session completely free and with no commitment.',
    ct_form_tag:'Write to us', ct_form_title:'Get in <span class="accent">touch</span>',
    ct_f_nombre:'First name *', ct_f_apellidos:'Last name', ct_f_email:'Email *', ct_f_tel:'Phone',
    ct_f_programa:'Programme of interest', ct_select:'Select...',
    ct_prog1:'i-Motion Sport (sports performance)', ct_prog2:'i-Shape Esthetic (body transformation)', ct_prog3:'Both programmes / Not sure yet',
    ct_f_fecha:'Preferred date for the session', ct_f_horario:'Preferred time',
    ct_h1:'Morning (8:00 – 13:00)', ct_h2:'Afternoon (13:00 – 18:00)', ct_h3:'Evening (18:00 – 21:00)', ct_h4:'Saturday (9:00 – 14:00)',
    ct_f_como:'How did you find us?',
    ct_c3:'Google / Internet search', ct_c4:'Friend or family recommendation', ct_c5:'Passing by the centre', ct_c6:'Other',
    ct_f_msg:'Message', ct_f_privacy:'I accept the <a href="politica-privacidad.html" style="color:var(--accent);">privacy policy</a> *',
    ct_submit:'Send booking request',
    ct_info_tag:'Information', ct_info_title:'Find us <span class="accent">here</span>',
    ct_phone:'Phone', ct_address:'Address', ct_hours_label:'Opening hours',
    ct_hours:'Monday to Friday: 8:00 – 21:00<br>Saturdays: 9:00 – 14:00',
  }
};

function applyLang(lang) {
  localStorage.setItem('imotion_lang', lang);
  document.documentElement.lang = lang;
  document.querySelectorAll('.lang-btn').forEach(b => b.classList.toggle('active', b.dataset.lang === lang));
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.dataset.i18n;
    if (T[lang] && T[lang][key] !== undefined) el.innerHTML = T[lang][key];
  });
}

document.addEventListener('DOMContentLoaded', () => {
  const saved = localStorage.getItem('imotion_lang') || 'es';
  applyLang(saved);
});
